require("dotenv").config();
const express = require("express");
const app = express();
const mongoose = require("mongoose");
const User = require("./models/user");

//express middleware (executes after getting request)
app.use(express.json());
//responds with the app when root of website is visited
app.use(express.static("build"));

const testUser = new User({
	name: "OCT FELLA",
	nric: "OINAVAOINAION",
	id: 139,
	questionOneObj: {
		a1: "",
		a2: "",
		a3: "",
		c1: "",
		c2: "",
		c3: "",
	},
	questionOneTEF: {
		InitialOrders: {
			OPLocation: "",
			OPHeight: "",
			OTDistance: "",
			CallSign: "",
			FireMission: "",
			TargetGrid: "",
			Altitude: "",
			Direction: "",
			LRInitialDirection: "",
			LRInitialAdjustment: "",
			ADInitialDirection: "",
			ADInitialAdjustment: "",
			Ammo: "",
			TargetDescription: "",
			Vegetation: "",
			TargetFrontBearing: "",
			TargetFrontLength: "",
			MissionType: "",
			CheckPE: "",
			CheckAngleT: "",
			MethodOfFireControl: "",
		},
		AdjustmentRowList: [
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
		],
		PRCorrections: {
			PRRound1GraphLeftRight: "-10",
			PRRound1GraphLongShort: "10",
			PRRound2GraphLeftRight: "10",
			PRRound2GraphLongShort: "10",
			PRRound3GraphLeftRight: "-10",
			PRRound3GraphLongShort: "-10",
			PRRound4GraphLeftRight: "10",
			PRRound4GraphLongShort: "-10",
			PRRound1Left: "",
			PRRound1Right: "",
			PRRound1LongShort: "",
			PRRound2Left: "",
			PRRound2Right: "",
			PRRound2LongShort: "",
			PRRound3Left: "",
			PRRound3Right: "",
			PRRound3LongShort: "",
			PRRound4Left: "",
			PRRound4Right: "",
			PRRound4LongShort: "",
			PRTotalLeft: "",
			PRTotalRight: "",
			PRNumberOfRounds: "",
			PRMean: "",
			PROTFactor: "",
			PRFinalOrdersLeft: "",
			PRFinalOrdersRight: "",
			PRFinalOrdersAddDrop: "",
			PRFinalOrdersAddDropAmmount: "",
			PRRecordAsPoint: "",
			ActivationCodeword: "",
			TargetCodeword: "",
		},
	},
	questionTwoObj: {
		b1: "",
		b2: "",
		b3: "",
		b4: "",
		b5: "",
		b6: "",
		b7: "",
		b8: "",
	},
	questionTwoTEF: {
		InitialOrders: {
			OPLocation: "",
			OPHeight: "",
			OTDistance: "",
			CallSign: "",
			FireMission: "",
			TargetGrid: "",
			Altitude: "thdhtdhtdh",
			Direction: "",
			LRInitialDirection: "",
			LRInitialAdjustment: "",
			ADInitialDirection: "",
			ADInitialAdjustment: "",
			Ammo: "",
			TargetDescription: "",
			Vegetation: "",
			TargetFrontBearing: "",
			TargetFrontLength: "",
			MissionType: "",
			CheckPE: "",
			CheckAngleT: "",
			MethodOfFireControl: "",
		},
		AdjustmentRowList: [
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
		],
		PRCorrections: {
			PRRound1GraphLeftRight: "-15",
			PRRound1GraphLongShort: "15",
			PRRound2GraphLeftRight: "10",
			PRRound2GraphLongShort: "10",
			PRRound3GraphLeftRight: "-30",
			PRRound3GraphLongShort: "-20",
			PRRound4GraphLeftRight: "10",
			PRRound4GraphLongShort: "-10",
			PRRound1Left: "",
			PRRound1Right: "",
			PRRound1LongShort: "",
			PRRound2Left: "",
			PRRound2Right: "",
			PRRound2LongShort: "",
			PRRound3Left: "",
			PRRound3Right: "",
			PRRound3LongShort: "",
			PRRound4Left: "",
			PRRound4Right: "",
			PRRound4LongShort: "",
			PRTotalLeft: "",
			PRTotalRight: "",
			PRNumberOfRounds: "",
			PRMean: "",
			PROTFactor: "",
			PRFinalOrdersLeft: "",
			PRFinalOrdersRight: "",
			PRFinalOrdersAddDrop: "",
			PRFinalOrdersAddDropAmmount: "",
			PRRecordAsPoint: "",
			ActivationCodeword: "",
			TargetCodeword: "",
		},
	},
	questionThreeObj: {
		c1: "",
		c2: "",
		c3: "",
		c4: "",
	},
	questionThreeTEF: {
		InitialOrders: {
			OPLocation: "",
			OPHeight: "",
			OTDistance: "",
			CallSign: "",
			FireMission: "",
			TargetGrid: "",
			Altitude: "",
			Direction: "",
			LRInitialDirection: "",
			LRInitialAdjustment: "",
			ADInitialDirection: "",
			ADInitialAdjustment: "",
			Ammo: "",
			TargetDescription: "",
			Vegetation: "",
			TargetFrontBearing: "",
			TargetFrontLength: "",
			MissionType: "",
			CheckPE: "",
			CheckAngleT: "",
			MethodOfFireControl: "",
		},
		AdjustmentRowList: [
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
		],
		PRCorrections: {
			PRRound1GraphLeftRight: "-10",
			PRRound1GraphLongShort: "10",
			PRRound2GraphLeftRight: "10",
			PRRound2GraphLongShort: "10",
			PRRound3GraphLeftRight: "-10",
			PRRound3GraphLongShort: "-10",
			PRRound4GraphLeftRight: "10",
			PRRound4GraphLongShort: "-10",
			PRRound1Left: "",
			PRRound1Right: "",
			PRRound1LongShort: "",
			PRRound2Left: "",
			PRRound2Right: "",
			PRRound2LongShort: "",
			PRRound3Left: "",
			PRRound3Right: "",
			PRRound3LongShort: "",
			PRRound4Left: "",
			PRRound4Right: "",
			PRRound4LongShort: "",
			PRTotalLeft: "",
			PRTotalRight: "",
			PRNumberOfRounds: "",
			PRMean: "",
			PROTFactor: "",
			PRFinalOrdersLeft: "",
			PRFinalOrdersRight: "",
			PRFinalOrdersAddDrop: "",
			PRFinalOrdersAddDropAmmount: "",
			PRRecordAsPoint: "",
			ActivationCodeword: "",
			TargetCodeword: "",
		},
	},
	questionFourObj: {
		b1: "",
		c1: "",
	},
	questionFourTEF: {
		InitialOrders: {
			OPLocation: "",
			OPHeight: "",
			OTDistance: "",
			CallSign: "",
			FireMission: "",
			TargetGrid: "",
			Altitude: "",
			Direction: "",
			LRInitialDirection: "",
			LRInitialAdjustment: "",
			ADInitialDirection: "",
			ADInitialAdjustment: "",
			Ammo: "",
			TargetDescription: "",
			Vegetation: "",
			TargetFrontBearing: "",
			TargetFrontLength: "",
			MissionType: "",
			CheckPE: "",
			CheckAngleT: "",
			MethodOfFireControl: "",
		},
		AdjustmentRowList: [
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
		],
		PRCorrections: {
			PRRound1GraphLeftRight: "-10",
			PRRound1GraphLongShort: "10",
			PRRound2GraphLeftRight: "10",
			PRRound2GraphLongShort: "10",
			PRRound3GraphLeftRight: "-10",
			PRRound3GraphLongShort: "-10",
			PRRound4GraphLeftRight: "10",
			PRRound4GraphLongShort: "-10",
			PRRound1Left: "",
			PRRound1Right: "",
			PRRound1LongShort: "",
			PRRound2Left: "",
			PRRound2Right: "",
			PRRound2LongShort: "",
			PRRound3Left: "",
			PRRound3Right: "",
			PRRound3LongShort: "",
			PRRound4Left: "",
			PRRound4Right: "",
			PRRound4LongShort: "",
			PRTotalLeft: "",
			PRTotalRight: "",
			PRNumberOfRounds: "",
			PRMean: "",
			PROTFactor: "",
			PRFinalOrdersLeft: "",
			PRFinalOrdersRight: "",
			PRFinalOrdersAddDrop: "",
			PRFinalOrdersAddDropAmmount: "",
			PRRecordAsPoint: "",
			ActivationCodeword: "",
			TargetCodeword: "",
		},
	},
	questionFiveTEF: {
		InitialOrders: {
			OPLocation: "",
			OPHeight: "",
			OTDistance: "",
			CallSign: "",
			FireMission: "",
			TargetGrid: "",
			Altitude: "",
			Direction: "",
			LRInitialDirection: "",
			LRInitialAdjustment: "",
			ADInitialDirection: "",
			ADInitialAdjustment: "",
			Ammo: "",
			TargetDescription: "",
			Vegetation: "",
			TargetFrontBearing: "",
			TargetFrontLength: "",
			MissionType: "",
			CheckPE: "",
			CheckAngleT: "",
			MethodOfFireControl: "",
		},
		AdjustmentRowList: [
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
			{
				Round: "",
				VRDirection: "",
				VRDistance: "",
				VRVerticalAngle: "",
				LRObservation: "",
				SLObservation: "",
				AmmoCorrection: "",
				LRCorrection: "",
				ADCorrection: "",
				AdditionalCorrection: "",
			},
		],
		PRCorrections: {
			PRRound1GraphLeftRight: "-10",
			PRRound1GraphLongShort: "10",
			PRRound2GraphLeftRight: "10",
			PRRound2GraphLongShort: "10",
			PRRound3GraphLeftRight: "-10",
			PRRound3GraphLongShort: "-10",
			PRRound4GraphLeftRight: "10",
			PRRound4GraphLongShort: "-10",
			PRRound1Left: "",
			PRRound1Right: "",
			PRRound1LongShort: "",
			PRRound2Left: "",
			PRRound2Right: "",
			PRRound2LongShort: "",
			PRRound3Left: "",
			PRRound3Right: "",
			PRRound3LongShort: "",
			PRRound4Left: "",
			PRRound4Right: "",
			PRRound4LongShort: "",
			PRTotalLeft: "",
			PRTotalRight: "",
			PRNumberOfRounds: "",
			PRMean: "",
			PROTFactor: "",
			PRFinalOrdersLeft: "",
			PRFinalOrdersRight: "",
			PRFinalOrdersAddDrop: "",
			PRFinalOrdersAddDropAmmount: "",
			PRRecordAsPoint: "",
			ActivationCodeword: "",
			TargetCodeword: "",
		},
	},
});

app.post("/api/users",(request,response)=>{
	console.log(request.body);
	const newUser=new User(request.body);
	newUser.save().then(dbResponse=>{
		response.json(dbResponse)
	})
	response.status(200)
	return ;
})


const PORT = process.env.PORT;
app.listen(PORT, () => {
	console.log(`backend server running on port ${PORT}`);
});
